MVC_Movie/Models/ErrorViewModel.cs
using System;

namespace MVC_Movie.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC_Movie/ViewModels/NhanVienCreateModel.cs
using System.Collections.Generic;
using Application.DTOs;

namespace MVC_Movie.ViewModels
{
    public class NhanVienCreateModel
    {
        public NhanVienDto NV { get; set; }
        public IEnumerable<QuyenDto> Quyens { get; set; }
        
    }
}

MVC_Movie/ViewModels/NhanVienViewModel.cs
using Application.DTOs;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC_Movie.Helpers;

namespace MVC_Movie.ViewModels
{
    public class NhanVienViewModel
    {
        public PaginatedList<NhanVienDto> NhanViens { get; set; } 
        public SelectList Quyens { get; set; }
        public string TypeQuyen { get; set; }
        public string SearchString { get; set; }
        public string SortString { get; set; }
    }
}

MVC_Movie/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Application.DTOs;
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC_Movie.Models;

namespace MVC_Movie.Controllers
{
    public class HomeController : Controller
    {
        private readonly IQuyenService quyenService;

        public HomeController(IQuyenService quyenService)
        {
            this.quyenService = quyenService;
        }

        public async Task<IActionResult> Index()
        {
            var quyens = await quyenService.GetAll();
            return View(quyens);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id) {
            var result = await quyenService.GetBy(id);
            try{
                if(result == null) {
                    ModelState.AddModelError("", "Không tồn tại quyền cần sửa");
                }
                return View(result);
            }
            catch(Exception e) {
                ModelState.AddModelError("", e.ToString());
                return View(result);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(QuyenDto quyenDto) {
            if(ModelState.IsValid) {
                try {
                    await quyenService.Update(quyenDto);
                    return RedirectToAction("Index");
                }
                catch(Exception e) {
                    ModelState.AddModelError("", e.ToString());
                    return View(quyenDto);
                }
            }
            return View(quyenDto);
        }

        // public IActionResult Privacy()
        // {
        //     return View();
        // }

        // [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        // public IActionResult Error()
        // {
        //     return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        // }
    }
}

MVC_Movie/Controllers/NhanVienController.cs
using System;
using System.Threading.Tasks;
using Application.DTOs;
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC_Movie.Helpers;
using MVC_Movie.ViewModels;

namespace MVC_Movie.Controllers
{
    public class NhanVienController : Controller
    {
        private readonly INhanVienService nhanVienService;
        private readonly IQuyenService quyenService;
        public NhanVienController(INhanVienService nhanVienService, IQuyenService quyenService) {
            this.nhanVienService = nhanVienService;
            this.quyenService = quyenService;
        }

        public async Task<IActionResult> Index(string sortString, string typeQuyen, string searchString, int pageIndex = 1) {
            int pageSize = 3;
            int count;
            var TypeQuyens = quyenService.GetNameAll();
            var idquyen = quyenService.GetIdByName(typeQuyen);
            var nhanviens = nhanVienService.Filter(idquyen, searchString, sortString, pageIndex, pageSize, out count);

            var NhanVienVM = new NhanVienViewModel() {
                NhanViens = new PaginatedList<NhanVienDto>(nhanviens, count, pageIndex, pageSize),
                Quyens = new SelectList(TypeQuyens),
                TypeQuyen = typeQuyen,
                SearchString = searchString,
                SortString = sortString
            };

            return View(NhanVienVM);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id) {
            var NV = await nhanVienService.GetBy(id);
            return View(NV);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, bool notUsed) {
            await nhanVienService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Create() {
            var IndexModel = new NhanVienCreateModel();
            IndexModel.Quyens = await quyenService.GetAll();
            return View(IndexModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(NhanVienCreateModel IndexModel) {
            IndexModel.Quyens = await quyenService.GetAll();
            if (ModelState.IsValid)
            {
                try
                {
                    // var nv = await nhanVienService.GetByUser(IndexModel.NV.user);
                    // if(nv != null) {
                    //     ModelState.AddModelError("", "Tài khoản đã tồn tại!");
                    //     return View(IndexModel);
                        
                    // }
                    // else {
                    //     var result = await nhanVienService.Add(IndexModel.NV);
                    //     return RedirectToAction("Index");
                    // }
                    var result = await nhanVienService.Add(IndexModel.NV);
                        return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    if(e.ToString().Contains("UNIQUE constraint failed: NhanViens.user")) {
                        // ModelState.AddModelError("", "Tài khoản đã tồn tại!");
                        ModelState.AddModelError("", e.ToString());
                    }else {
                        ModelState.AddModelError("", e.ToString());
                    }
                    return View(IndexModel);
                }
            }

            return View(IndexModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id) {
            var IndexModel = new NhanVienCreateModel();
            try{
                IndexModel.Quyens = await quyenService.GetAll();
                IndexModel.NV = await nhanVienService.GetBy(id);
                if(IndexModel.NV == null) {
                    ModelState.AddModelError("", "Không tồn tại nhân viên cần sửa");
                }
                return View(IndexModel);
            }
            catch(Exception e) {
                ModelState.AddModelError("", e.ToString());
                return View(IndexModel);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(NhanVienCreateModel IndexModel) {
            IndexModel.Quyens = await quyenService.GetAll();
            if(ModelState.IsValid) {
                try{
                    var nv = nhanVienService.GetBy(IndexModel.NV.nhanvienId);
                    if(nv == null) {
                        ModelState.AddModelError("", $"Không tồn tại ID = {IndexModel.NV.nhanvienId}");
                        return View(IndexModel);
                    }
                    
                    var result = await nhanVienService.UpdateByUser(IndexModel.NV);
                    if(result == null) {
                        ModelState.AddModelError("", "Update thất bại");
                        return View(IndexModel);
                    }
                    // await nhanVienService.Update(IndexModel.NV);
                    return RedirectToAction("Index");
                }
                catch(Exception e) {
                    ModelState.AddModelError("", e.ToString());
                    return View(IndexModel);
                }
            }
            return View(IndexModel);
        }
    }
}

MVC_Movie/Controllers/QuyenController.cs
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace MVC_Movie.Controllers
{
    public class QuyenController : Controller
    {
        private readonly IQuyenService quyenService;
        public QuyenController(IQuyenService quyenService) {
            this.quyenService = quyenService;
        }
    }
}

MVC_Movie/Views/Home/Edit.cshtml
@model Application.DTOs.QuyenDto;

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<h4>Quyền</h4>
<hr/>

<div class="row">
    <div class="col-md-4">
        <form method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
                <label asp-for="@Model.Id" class="control-label"></label>
                <input asp-for="@Model.Id" class="form-control"/>
                <span asp-validation-for="@Model.Id" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="@Model.name" class="control-label"></label>
                <input asp-for="@Model.name" class="form-control"/>
                <span asp-validation-for="@Model.name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.detail" class="control-label"></label>
                <textarea asp-for="@Model.detail" class="form-control"></textarea>
                <span asp-validation-for="@Model.detail" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_Movie/Views/Home/Index.cshtml
@* @model Application.ViewDTOs.LoginDto;
@{
    ViewData["Title"] = "Login Admin";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>@ViewData["Title"]</title>
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <style>
        .field-validation-error {
            color: red
        }

        .validation-summary-errors {
            color: red
        }
    </style>
    <script src="~/js/Validate-client/jquery-2.2.0.min.js"></script>
    <script src="~/js/Validate-client/jquery.validate.min.js"></script>
    <script src="~/js/Validate-client/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <section class="container">
        <div class="login">
            <h1>Đăng nhập Admin</h1>
            <form method="post" action="/Admin/Login/Index">
                <div asp-validation-summary="ModelOnly"></div>
                <p><input type="text" asp-for="@Model.user" placeholder="Tài khoản"></p>
                <span asp-validation-for="@Model.user"></span>
                <p><input type="password" asp-for="@Model.password" placeholder="Mật khẩu"></p>
                <span asp-validation-for="@Model.password"></span>
                <p class="submit"><input type="submit" name="commit" value="Login"></p>
            </form>
        </div>
    </section>

    <script type="text/javascript">
    function cc(){
        // onsubmit="return(cc());"
      var x = document.forms[0].login.value;
      var y = document.forms[0].password.value;
      alert(x + " " + y);
      return false;
    }
    </script>
</body>
</html> *@


@{
    ViewData["Title"] = "Home Page";
}
@model IEnumerable<Application.DTOs.QuyenDto>

<div class="text-center">
    <table>
        @{
            if(Model != null) {
                foreach(var q in Model) {
                    <tr>
                        <td>@q.QuyenId</td>
                        <td>@q.name</td>
                        <td>@q.detail</td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@q.QuyenId">Edit</a> |
                            <a asp-action="Details" asp-route-id="@q.QuyenId">Details</a> |
                            <a asp-action="Delete" asp-route-id="@q.QuyenId">Delete</a>
                        </td>
                    </tr>
                }
            }
        }
    </table>
</div>

MVC_Movie/Views/NhanVien/Create.cshtml
@model NhanVienCreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<h4>Movie</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
                <label asp-for="@Model.NV.Id" class="control-label"></label>
                <input asp-for="@Model.NV.Id" class="form-control"/>
                <span asp-validation-for="@Model.NV.Id" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="@Model.NV.user" class="control-label"></label>
                <input asp-for="@Model.NV.user" class="form-control"/>
                <span asp-validation-for="@Model.NV.user" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.password" class="control-label"></label>
                <input asp-for="@Model.NV.password" class="form-control"/>
                <span asp-validation-for="@Model.NV.password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.repass" class="control-label"></label>
                <input asp-for="@Model.NV.repass" class="form-control"/>
                <span asp-validation-for="@Model.NV.repass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.full_name" class="control-label"></label>
                <input asp-for="@Model.NV.full_name" class="form-control"/>
                <span asp-validation-for="@Model.NV.full_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.phone" class="control-label"></label>
                <input asp-for="@Model.NV.phone" class="form-control"/>
                <span asp-validation-for="@Model.NV.phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.mail" class="control-label"></label>
                <input asp-for="@Model.NV.mail" class="form-control"/>
                <span asp-validation-for="@Model.NV.mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.address" class="control-label"></label>
                <input asp-for="@Model.NV.address" class="form-control"/>
                <span asp-validation-for="@Model.NV.address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.gender" class="control-label"></label>

                <div class="form-check-inline">
                    <label class="form-check-label">
                        @Html.RadioButtonFor(model => model.NV.gender, "Nam", new {style = "width:63%;"}) Nam
                    </label>
                </div>
                
                <div class="form-check-inline">
                    <label class="form-check-label">
                        @Html.RadioButtonFor(model => model.NV.gender, "Nữ") Nữ
                    </label>
                </div>

                @* <input asp-for="@Model.NV.gender" class="form-control"/> *@
                <span asp-validation-for="@Model.NV.gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.dateborn" class="control-label"></label>
                <input asp-for="@Model.NV.dateborn" type="date" class="form-control"/>
                <span asp-validation-for="@Model.NV.dateborn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.QuyenId" class="control-label"></label>
                <select asp-for="@Model.NV.QuyenId">
                    @{
                        foreach(var q in Model.Quyens) {
                            <option value="@q.QuyenId">@q.name</option>
                        }
                    }
                </select>
                @* <input asp-for="@Model.NV.QuyenId" class="form-control"/> *@
                <span asp-validation-for="@Model.NV.QuyenId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

@* @if (ViewBag.Message != null)
{
    <script type="text/javascript">
        window.onload = function () {
            if('@ViewBag.Message.ToString()' == 'T&#xE0;i kho&#x1EA3;n &#x111;&#xE3; t&#x1ED3;n t&#x1EA1;i') {
                alert("Tài khoản đã tồn tại");
            }
            else {
                alert('@ViewBag.Message.ToString()');
            }
            
        };
    </script>
} *@

MVC_Movie/Views/NhanVien/Delete.cshtml
@model NhanVienDto

@{
    ViewData["Title"] = "Delete Page";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Nhân Viên</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.nhanvienId)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.nhanvienId)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.user)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.user)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.full_name)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.full_name)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.phone)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.phone)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.mail)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.mail)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.address)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.address)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.gender)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.gender)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.dateborn)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.dateborn)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.QuyenId)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.QuyenId)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.status_active)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.status_active)</dd>
    </dl>

    <form method="POST">
        <input type="hidden" asp-route-id="@Model.nhanvienId"/>
        <input type="submit" value="Delete" class="btn btn-danger"/>
        <a asp-action="Index">Back to list</a>
    </form>
</div>

MVC_Movie/Views/NhanVien/Edit.cshtml
@model NhanVienCreateModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<h4>Movie</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="@Model.NV.nhanvienId" class="control-label"></label>
                <input asp-for="@Model.NV.nhanvienId" class="form-control" readonly/>
                <span asp-validation-for="@Model.NV.nhanvienId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.user" class="control-label"></label>
                <input asp-for="@Model.NV.user" class="form-control" readonly/>
                <span asp-validation-for="@Model.NV.user" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.password" class="control-label"></label>
                <input asp-for="@Model.NV.password" class="form-control"/>
                <span asp-validation-for="@Model.NV.password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.repass" class="control-label"></label>
                <input asp-for="@Model.NV.repass" class="form-control"/>
                <span asp-validation-for="@Model.NV.repass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.full_name" class="control-label"></label>
                <input asp-for="@Model.NV.full_name" class="form-control"/>
                <span asp-validation-for="@Model.NV.full_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.phone" class="control-label"></label>
                <input asp-for="@Model.NV.phone" class="form-control"/>
                <span asp-validation-for="@Model.NV.phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.mail" class="control-label"></label>
                <input asp-for="@Model.NV.mail" class="form-control"/>
                <span asp-validation-for="@Model.NV.mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.address" class="control-label"></label>
                <input asp-for="@Model.NV.address" class="form-control"/>
                <span asp-validation-for="@Model.NV.address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.gender" class="control-label"></label>

                <div class="form-check-inline">
                    <label class="form-check-label">
                        @Html.RadioButtonFor(model => model.NV.gender, "Nam", new {style = "width:63%;"}) Nam
                    </label>
                </div>
                
                <div class="form-check-inline">
                    <label class="form-check-label">
                        @Html.RadioButtonFor(model => model.NV.gender, "Nữ") Nữ
                    </label>
                </div>

                @* <input asp-for="@Model.NV.gender" class="form-control"/> *@
                <span asp-validation-for="@Model.NV.gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.dateborn" class="control-label"></label>
                <input asp-for="@Model.NV.dateborn" type="date" class="form-control"/>
                <span asp-validation-for="@Model.NV.dateborn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NV.QuyenId" class="control-label"></label>
                <select asp-for="@Model.NV.QuyenId">
                    @{
                        foreach(var q in Model.Quyens) {
                            <option value="@q.QuyenId">@q.name</option>
                        }
                    }
                </select>
                @* <input asp-for="@Model.NV.QuyenId" class="form-control"/> *@
                <span asp-validation-for="@Model.NV.QuyenId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_Movie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Movie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="NhanVien" asp-action="Index">Staff</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>